Install @carbon/ibmdotcom-web-components package
Qiskit/web-components pull request #129
Opened 2022-07-26 16:03 UTC by abdonrd

## Changes

Install @carbon/ibmdotcom-web-components package

2022-07-26 16:06 UTC, abdonrd commented on package.json
> +      "typescript": "$typescript"
This does the trick.

2022-07-26 16:06 UTC, abdonrd commented on package.json
> +    "@carbon/ibmdotcom-web-components": "^1.22.0-nightly",
I use the nightly because this is not released yet:
- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9089

2022-07-26 16:06 UTC, abdonrd commented on package.json
> +    "npm": ">=8.3.0"
Needed to use the `overrides` field.

2022-08-02 13:16 UTC, y4izus requested changes
Reading [this](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components#:~:text=ibmdotcom%2Dweb%2Dcomponents-,NOTE,-%3A%20Lit%20dependencies%20will), it looks like we can remove `lit-element` and `lit-html` from our `package.json`

2022-08-03 06:50 UTC, abdonrd commented
> Reading [this](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/tree/main/packages/web-components#:~:text=ibmdotcom%2Dweb%2Dcomponents-,NOTE,-%3A%20Lit%20dependencies%20will), it looks like we can remove `lit-element` and `lit-html` from our `package.json`

Yes and no...

https://github.com/Qiskit/web-components/blob/c02b2a0a1aba3e11687e2f38dfcca2e53884f920/package.json#L50-L52

`@carbon/ibmdotcom-web-components` use Lit v1: `lit-html@1` and `lit-element@2`
We use Lit v2: `lit-html@2` and `lit-element@3`

If remove `lit-html` and `lit-element` in the `package.json`...
npm will resolve `lit-html@1` and `lit-element@2` in the root, instead of `lit-html@2` and `lit-element@3`
So we need it to force the npm packages resolve (unless until `@carbon/ibmdotcom-web-components` start using Lit v2)

2022-08-17 16:45 UTC, abdonrd commented on package.json
> +    "@carbon/ibmdotcom-web-components": "^1.22.0-nightly",
Updated!

2022-09-09 08:42 UTC, Tansito commented
@abdonrd @y4izus taking into account that we are not going to need this package by now do you think we can close this PR? (very interesting anyway for futures insights)

2022-09-09 10:59 UTC, abdonrd commented
Yes!

2022-09-09 10:59 UTC, closed without merging